import { test, expect, type Page } from '@playwright/test'
import { emptyStore, importToPersonal, installBook, reviewWord, validateStore, type Store } from '../src/model'
import { starterRows } from '../src/vocabulary'

/** 朗读本组 / 回看当天 / 撤销上一步 / 重新开始本组 sit in the 复习计划 sheet; open it once and query inside. */
async function studyMenu(page: Page) {
  const tools = page.getByRole('group', { name: '本组操作' })
  if (!(await tools.isVisible())) await page.getByRole('button', { name: '复习计划', exact: true }).click()
  await expect(tools).toBeVisible()
  return tools
}


const fixture = (count = 40) => importToPersonal({ ...emptyStore(), goal: 40 }, starterRows.slice(0, count), '学习回归').store
/** Due-date review across books is FSRS behaviour; 艾宾浩斯 reviews by study day. */
const fsrsFixture = (count = 40): Store => ({ ...fixture(count), reviewMethod: 'fsrs' })
/** Saves run in the background now; wait until the page has nothing in flight, then read the device copy. */
async function settled(page: Page) {
  if (page.url().startsWith('http')) await page.waitForFunction(() => document.documentElement.dataset.saving !== 'true', null, { timeout: 15000 })
}
const state = async (page: Page): Promise<Store> => { await settled(page); return (await (await page.request.get('/api/state')).json()).state }
async function seed(page: Page, store: Store) {
  const { revision } = await (await page.request.get('/api/state')).json()
  expect((await page.request.put('/api/state', { data: { state: validateStore(store), revision } })).status()).toBe(200)
}
const submit = (page: Page) => page.getByRole('button', { name: '本组已检查完', exact: true })
test.afterEach(async ({ context }) => {
  for (const page of context.pages()) await page.close()
  expect(context.pages()).toHaveLength(0)
})

async function openStory(page: Page) {
  await page.getByRole('button', { name: '复习计划', exact: true }).click()
  await page.getByRole('group', { name: '本组操作' }).getByRole('button', { name: '读短文', exact: true }).click()
}
test('all main pages share clear navigation and return to the same study group', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await seed(page, fixture(60))
  await page.goto('/')
  const nav = page.getByRole('navigation', { name: '主导航' })
  await expect(nav.getByRole('tab')).toHaveCount(4)
  await expect(page.getByRole('heading', { name: '学习', exact: true })).toHaveCount(1)
  await page.getByRole('button', { name: '快速记忆', exact: true }).click()
  await expect(page.locator('.card-meaning')).toHaveCount(20)
  const task = (await state(page)).learning.drafts.learn!
  await page.getByRole('button', { name: '自己自查', exact: true }).click()
  await page.getByRole('button', { name: '显示全部释义', exact: true }).click()
  const firstMeaning = page.locator('.meaning-entry').first()
  expect((await firstMeaning.locator('.chinese-meaning').boundingBox())!.width).toBeGreaterThan(120)
  await expect(page.locator('.meaning-dict')).toHaveCount(0)
  await page.getByRole('button', { name: '第 01 词词典释义', exact: true }).click()
  await expect(firstMeaning.locator('.meaning-dict')).toContainText(starterRows[0].meaning.split('\n')[0].trim())
  await expect(page.getByRole('button', { name: '第 01 词词典释义', exact: true })).toHaveAttribute('aria-expanded', 'true')
  await page.getByRole('button', { name: '第 02 词词典释义', exact: true }).click()
  await expect(page.locator('.meaning-dict')).toHaveCount(1)
  await page.getByRole('button', { name: '标记第 01 词不熟', exact: true }).click()
  await expect(page.getByRole('button', { name: '取消第 01 词不熟', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: '取消第 01 词不熟', exact: true }).click()
  await page.getByRole('button', { name: '隐藏全部释义', exact: true }).click()
  await openStory(page)
  // No key was ever entered: the story comes from the built-in AI instead of a setup screen.
  await expect(page.getByRole('button', { name: '设置 AI 服务', exact: true })).toHaveCount(0)
  const builtIn: { mode: string; words: { id: string; word: string; meaning: string }[] }[] = []
  await page.route('**/v1/ai/reading', async route => {
    const cors = { 'access-control-allow-origin': '*', 'access-control-allow-headers': 'content-type', 'access-control-allow-methods': 'POST' }
    if (route.request().method() === 'OPTIONS') return route.fulfill({ status: 204, headers: cors })
    const body = route.request().postDataJSON(); builtIn.push(body)
    await route.fulfill({ headers: cors, json: { model: 'built-in-fixture', story: { title: 'Built In', paragraphs: [{ english: `We use ${body.words.map((w: { word: string }) => w.word).join(', ')}.`, translation: '内置 AI 合成短文。' }] } } })
  })
  await page.getByRole('button', { name: '生成本组短文', exact: true }).click()
  await expect(page.locator('.context-reader .story-article h2')).toHaveText('Built In')
  expect(builtIn).toHaveLength(1)
  expect(builtIn[0].mode).toBe('story')
  expect(builtIn[0].words).toHaveLength(20)
  expect((await state(page)).contextStories[0]).toMatchObject({ taskId: task.id, model: 'built-in-fixture' })
  await expect(page.locator('.context-reader')).toHaveAttribute('data-task-id', task.id)
  await page.getByRole('button', { name: '自己自查', exact: true }).click()
  await expect(page.locator('.english-grid')).toHaveCSS('opacity', '1')
  await page.screenshot({ path: 'test-results/flow-study-390.png', animations: 'disabled' })
  expect((await state(page)).reviews).toHaveLength(0)
  await nav.getByRole('tab', { name: '统计', exact: true }).click()
  await expect(page.getByRole('heading', { name: '统计', exact: true })).toBeVisible()
  await expect(nav.getByRole('tab', { name: '统计', exact: true })).toHaveAttribute('aria-selected', 'true')
  await page.screenshot({ path: 'test-results/flow-stats-390.png', animations: 'disabled' })
  await page.getByRole('button', { name: '我的单词', exact: true }).click()
  await page.getByRole('button', { name: '已标记', exact: true }).click()
  await expect(page.getByRole('button', { name: '查看全部单词', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '查看全部单词', exact: true }).click()
  await page.screenshot({ path: 'test-results/flow-library-390.png', animations: 'disabled' })
  await page.getByRole('button', { name: '返回', exact: true }).click()
  await expect(page.getByRole('heading', { name: '统计', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '考频查询', exact: true }).click()
  await expect(page.locator('.frequency-table')).toBeVisible()
  await page.screenshot({ path: 'test-results/flow-frequency-390.png', animations: 'disabled' })
  await nav.getByRole('tab', { name: '我的', exact: true }).click()
  await page.getByRole('button', { name: '管理目标词书', exact: true }).click()
  await expect(page.getByRole('heading', { name: '词书管理', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '添加词书', exact: true }).click()
  await expect(page.locator('.catalog-book').first()).toBeVisible()
  await page.screenshot({ path: 'test-results/flow-catalog-390.png', animations: 'disabled' })
  await nav.getByRole('tab', { name: '阅读', exact: true }).click()
  await page.screenshot({ path: 'test-results/flow-reading-hub-390.png', animations: 'disabled' })
  await page.getByRole('button', { name: '每日英语选读', exact: true }).click()
  await page.getByRole('button', { name: '英语选读', exact: true }).click()
  await expect(page.locator('.source-article')).toBeVisible()
  await page.screenshot({ path: 'test-results/flow-reading-390.png', animations: 'disabled' })
  await page.getByRole('button', { name: '完成阅读', exact: true }).click()
  await page.getByRole('button', { name: '读下一篇', exact: true }).click()
  await expect(page.getByRole('button', { name: '完成阅读', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: '返回', exact: true }).click()
  await page.getByRole('button', { name: '返回', exact: true }).click()
  await nav.getByRole('tab', { name: '学习', exact: true }).click()
  await openStory(page)
  await expect(page.locator('.context-reader')).toHaveAttribute('data-task-id', task.id)
  expect((await state(page)).reviews).toHaveLength(0)
  await page.getByRole('button', { name: '自己自查', exact: true }).click()
  await nav.getByRole('tab', { name: '我的', exact: true }).click()
  await expect(page.locator('.profile-summary')).toBeVisible()
  await page.screenshot({ path: 'test-results/flow-profile-390.png', animations: 'disabled' })
  for (const [label, slug] of [['学习设置', 'learning'], ['外观', 'appearance'], ['发音与阅读', 'voice'], ['AI 服务', 'ai'], ['数据与备份', 'data']]) {
    await page.getByRole('button', { name: label, exact: true }).click()
    await expect(page.getByRole('heading', { name: label, exact: true })).toBeVisible()
    for (const width of [320, 390, 1440]) {
      await page.setViewportSize({ width, height: 900 })
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
      expect(await page.locator('.settings-layout').evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
      await page.screenshot({ path: `test-results/flow-settings-${slug}-${width}.png`, animations: 'disabled' })
    }
    await page.setViewportSize({ width: 390, height: 844 })
    await page.getByRole('button', { name: '返回', exact: true }).click()
  }
  await nav.getByRole('tab', { name: '学习', exact: true }).click()
  expect((await state(page)).learning.drafts.learn!.id).toBe(task.id)
  await submit(page).click()
  await expect(page.getByRole('button', { name: '继续下一组', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '继续下一组', exact: true }).click()
  await expect(page.locator('.english-entry').first()).toHaveAttribute('data-word-id', task.groups[1][0])
  await nav.getByRole('tab', { name: '我的', exact: true }).click()
  await page.getByRole('button', { name: '外观', exact: true }).click()
  await page.getByRole('button', { name: '深色', exact: true }).click()
  await page.getByRole('group', { name: '其他文字' }).getByRole('button', { name: '大', exact: true }).click()
  const toastClose = page.locator('ion-toast').getByRole('button', { name: '关闭', exact: true })
  if (await toastClose.isVisible()) await toastClose.click()
  for (const width of [320, 430, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    for (const label of ['学习', '统计', '阅读', '我的']) {
      await nav.getByRole('tab', { name: label, exact: true }).click()
      await expect(page.getByRole('heading', { name: label, exact: true })).toBeVisible()
      await expect(page.locator('.view-transition')).toHaveCSS('opacity', '1')
      if (label === '学习') await expect(page.locator('.english-grid')).toHaveCSS('opacity', '1')
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
      expect(await page.locator('.content').evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
      await page.screenshot({ path: `test-results/flow-dark-${label}-${width}.png`, animations: 'disabled' })
    }
  }
})

test('study header has direct controls: no vague ⋯ menu, plan sheet holds the group tools', async ({ page }) => {
  await seed(page, fixture(40))
  for (const width of [320, 390]) {
    await page.setViewportSize({ width, height: 844 })
    await page.goto('/')
    await expect(page.getByRole('button', { name: '更多操作' })).toHaveCount(0)
    const plan = page.getByRole('button', { name: '复习计划', exact: true })
    await expect(plan).toBeVisible()
    await page.screenshot({ path: `test-results/study-header-${width}.png`, clip: { x: 0, y: 0, width, height: 160 }, animations: 'disabled' })
    expect(await page.locator('.study-card-top').evaluate(el => el.scrollWidth - el.clientWidth)).toBeLessThanOrEqual(0)
    expect(await plan.evaluate(el => el.getBoundingClientRect().right <= innerWidth)).toBe(true)
  }
  // 读短文 lives in the plan sheet, not in the crowded header.
  await expect(page.getByRole('button', { name: '读短文', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '复习计划', exact: true }).click()
  const tools = page.getByRole('group', { name: '本组操作' })
  for (const name of ['读短文', '朗读本组', '撤销上一步']) await expect(tools.getByRole('button', { name })).toBeVisible()
  await expect(tools.getByRole('button', { name: /^回看当天/ })).toBeVisible()
})
test('story generation shows a live progress card that goes calm under reduced motion', async ({ page }) => {
  await seed(page, fixture(40))
  let release: (() => void) | undefined
  await page.route('**/api/settings', route => route.fulfill({ json: { provider: 'deepseek', model: 'fixture-model', configured: true } }))
  await page.route('**/api/story', async route => {
    await new Promise<void>(resolve => { release = resolve })
    await route.fulfill({ json: { model: 'fixture-model', story: { title: 'Calm Progress', paragraphs: [{ english: 'A short fixture story.', translation: '合成短文。' }] } } })
  })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await openStory(page)
  await page.getByRole('button', { name: '生成本组短文', exact: true }).click()
  const progress = page.locator('.story-progress')
  await expect(progress).toBeVisible()
  expect(await progress.evaluate(el => getComputedStyle(el, '::before').animationName)).toBe('ai-orbit')
  expect(await progress.locator('.ai-icon-active').count()).toBe(1)
  await page.screenshot({ path: 'test-results/story-progress-390.png' })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  expect(await progress.evaluate(el => getComputedStyle(el, '::before').animationName)).toBe('none')
  release!()
  await expect(page.locator('.context-reader .story-article h2')).toHaveText('Calm Progress')
})

test('review progress separates the current task from later due words and resumes the first unfinished group', async ({ page }) => {
  const started = new Date()
  let initial = fsrsFixture(61)
  // FSRS short-term steps: a new word rated Good comes back after 10 minutes, a forgotten one after 1.
  for (const word of initial.words.slice(0, 40)) initial = reviewWord(initial, word.id, 3, new Date(+started - 30 * 60000))
  initial = reviewWord(initial, initial.words[40].id, 3, new Date(+started - 5 * 60000))
  initial.learning.view = 'review'
  await seed(page, initial)
  await page.clock.install({ time: started })
  await page.goto('/')
  await expect(page.getByRole('button', { name: '到期复习', exact: true })).toHaveText('到期复习 40')
  await page.locator('.english-line').first().click()
  const draft = (await state(page)).learning.drafts.review!
  await submit(page).click()
  await expect(page.getByLabel('本次任务进度')).toContainText('已完成 1 / 2 组')
  await page.clock.fastForward(6 * 60000)
  await expect(page.getByRole('button', { name: '到期复习', exact: true })).toHaveText('到期复习 22')
  await expect(page.getByLabel('本次任务进度')).toContainText('另有 2 词到期')
  await page.reload()
  await expect(page.getByLabel('本次任务进度')).toContainText('已完成 1 / 2 组')
  expect((await state(page)).learning.drafts.review!.id).toBe(draft.id)
  for (const width of [320, 390, 430, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    expect(await page.locator('.study-task-tabs,.study-draft-note').evaluateAll(items => items.every(el => el.scrollWidth <= el.clientWidth))).toBe(true)
    await page.screenshot({ path: `test-results/task-progress-${width}.png`, animations: 'disabled' })
  }
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: '复习计划', exact: true }).click()
  await expect(page.getByLabel('复习任务进度')).toContainText('本次已完成 1 / 2 组')
  await expect(page.getByLabel('复习任务进度')).toContainText('另有 2 词到期')
  await page.screenshot({ path: 'test-results/review-plan-progress-390.png', animations: 'disabled' })
  await page.getByRole('button', { name: '继续本次复习 · 剩余 1 组', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.locator('.english-entry').first()).toHaveAttribute('data-word-id', draft.groups[1][0])
  expect((await state(page)).learning.drafts.review!.id).toBe(draft.id)
  await submit(page).click()
  await expect(page.getByLabel('本次任务进度')).toContainText('已完成 2 / 2 组')
  await page.getByRole('button', { name: '复习计划', exact: true }).click()
  await page.getByRole('button', { name: '开始到期复习 · 2 词', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.locator('.english-entry')).toHaveCount(2)
  const continued = (await state(page)).learning.drafts.review!
  expect(continued.id).not.toBe(draft.id)
  expect(new Set(continued.groups.flat())).toEqual(new Set([draft.groups[0][0], initial.words[40].id]))
  await submit(page).click()
  await expect(page.getByRole('button', { name: '到期复习', exact: true })).toHaveText('到期复习 0')
  await page.getByRole('button', { name: '学习新词', exact: true }).click()
  // With nothing due, the 新词 / 到期复习 switch is hidden and the page shows new words directly.
  await expect(page.getByRole('group', { name: '学习任务' })).toHaveCount(0)
  await expect.poll(async () => (await state(page)).learning.view).toBe('learn')
})

test('empty review explains the next due time and provides a working new-word action', async ({ page }) => {
  let initial = fsrsFixture(20)
  initial = reviewWord(initial, initial.words[0].id, 3, new Date())
  initial.learning.view = 'review'
  await seed(page, initial); await page.goto('/')
  await expect(page.getByRole('heading', { name: '暂无到期复习' })).toBeVisible()
  await expect(page.locator('.study-empty')).toContainText('下次复习在')
  await page.getByRole('button', { name: '学习当天新词', exact: true }).click()
  await expect(page.locator('.english-entry')).toHaveCount(19)
  expect((await state(page)).reviews).toHaveLength(1)
})

test('unit selection and unfinished word groups stay aligned across switches and reloads', async ({ page }) => {
  const initial = fixture(81)
  await seed(page, initial); await page.goto('/')
  await page.locator('.english-line').first().click()
  const first = (await state(page)).learning.drafts.learn!
  await expect(submit(page)).toBeEnabled()
  await page.getByRole('slider', { name: '词组', exact: true }).focus(); await page.keyboard.press('ArrowRight')
  await expect.poll(async () => (await state(page)).learning.drafts.learn?.page).toBe(1)
  await expect(page.locator('.english-entry').first()).toHaveAttribute('data-word-id', initial.books[0].wordIds[20])
  await page.getByRole('button', { name: '后一天', exact: true }).click()
  await expect(page.locator('.day-title')).toHaveText('第 2 天')
  await expect(page.locator('.english-entry').first()).toHaveAttribute('data-word-id', initial.books[0].wordIds[40])
  await page.locator('.english-line').nth(1).click()
  await page.reload()
  await expect(page.locator('.english-entry').nth(1)).toHaveAttribute('data-forgotten', 'true')
  await page.getByRole('button', { name: '前一天', exact: true }).click()
  await expect(page.locator('.english-entry').first()).toHaveAttribute('data-word-id', initial.books[0].wordIds[20])
  expect((await state(page)).learning.drafts.learn!.id).toBe(first.id)
  await page.getByRole('button', { name: '上一组', exact: true }).click()
  await expect(page.locator('.english-entry').first()).toHaveAttribute('data-forgotten', 'true')
  expect((await state(page)).reviews).toHaveLength(0)
})

for (const kind of ['learn', 'review'] as const) test(`context ${kind} uses the exact saved group and returns to its self-test before grading`, async ({ page }) => {
  let initial = kind === 'review' ? fsrsFixture(61) : fixture(61)
  if (kind === 'review') {
    initial = installBook(initial, 'second', '第二词书', '合成测试', starterRows.slice(20, 61), 20)
    for (const word of initial.words.slice(0, 40)) initial = reviewWord(initial, word.id, 3, new Date(Date.now() - 30 * 60000))
    initial.activeBookId = 'personal'
  }
  initial.learning.view = kind
  await seed(page, initial)
  await page.route('**/api/settings', route => route.fulfill({ json: { provider: 'deepseek', model: 'fixture-model', configured: true } }))
  const requests: string[][] = []
  await page.route('**/api/story', async route => {
    const ids = route.request().postDataJSON().ids as string[]
    requests.push(ids)
    await route.fulfill({ json: { model: 'fixture-model', story: { title: 'Learning in Context', paragraphs: [{ english: `We remember ${ids.map(id => initial.words.find(w => w.id === id)!.word).join(', ')}.`, translation: '合成检查短文，非实际 AI 生成。' }] } } })
  })
  await page.goto('/')
  if (kind === 'review') {
    await expect(page.locator('.current-book-label')).toHaveText('全部词书')
    await expect(page.getByRole('button', { name: '选择学习的天' })).toHaveCount(0)
  }
  await page.getByRole('slider', { name: '词组', exact: true }).focus(); await page.keyboard.press('ArrowRight')
  await expect.poll(async () => (await state(page)).learning.drafts[kind]?.page).toBe(1)
  await expect(page.getByRole('slider', { name: '词组', exact: true })).toHaveAttribute('aria-valuenow', '2')
  const ids = await page.locator('.english-entry').evaluateAll(rows => rows.map(row => row.getAttribute('data-word-id')!))
  const before = await state(page), taskId = before.learning.drafts[kind]!.id
  await openStory(page)
  await page.getByRole('button', { name: '生成本组短文', exact: true }).click()
  await expect(page.locator('.context-reader .story-article')).toBeVisible()
  expect(requests).toEqual([ids])
  await page.getByRole('button', { name: `查看 ${initial.words.find(w => w.id === ids[0])!.word}`, exact: true }).click()
  await page.getByRole('dialog', { name: '阅读查词' }).getByRole('button', { name: '词条详情', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '单词详情' })).toBeVisible()
  await page.locator('ion-modal').getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByRole('button', { name: '关闭查词', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.reload()
  await expect(page.locator('.context-reader')).toHaveAttribute('data-task-id', taskId)
  await expect(page.locator('.context-reader')).toHaveAttribute('data-group', '1')
  await expect(page.locator('.story-article')).toBeVisible()
  expect(requests).toHaveLength(1)
  if (kind === 'learn') for (const width of [320, 390, 430, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    expect(await page.locator('.context-reader,.study-topbar,.study-tools').evaluateAll(items => items.every(el => el.scrollWidth <= el.clientWidth))).toBe(true)
    await page.screenshot({ path: `test-results/context-${width}.png`, animations: 'disabled' })
  }
  const read = await state(page)
  expect(read.words).toEqual(before.words); expect(read.reviews).toEqual(before.reviews)
  await page.getByRole('button', { name: '进入本组遮义自测', exact: true }).click()
  await expect(page.locator('.english-entry')).toHaveCount(ids.length)
  expect(await page.locator('.english-entry').evaluateAll(rows => rows.map(row => row.getAttribute('data-word-id')!))).toEqual(ids)
  await expect(page.locator('.chinese-meaning')).toHaveCount(0)
  expect((await state(page)).learning.drafts[kind]!.id).toBe(taskId)
  await page.locator('.english-line').first().click()
  await submit(page).click()
  await expect.poll(async () => (await state(page)).reviews.length).toBe(before.reviews.length + 20)
  const saved = await state(page)
  expect(saved.reviews.slice(-20).map(r => r.wordId)).toEqual(ids)
  expect(saved.reviews.slice(-20).filter(r => r.rating === 1)).toHaveLength(1)
  expect(saved.reviews.slice(-20).every(r => r.kind === kind)).toBe(true)
})

test('fixed groups recover after reload; submission and undo survive reload without duplicate reviews', async ({ page }) => {
  const initial = fixture()
  await seed(page, initial); await page.goto('/')
  for (let i = 0; i < 5; i++) await page.locator('.english-line').nth(i).click()
  // A tap always adds a mark; tapping a 本轮不熟 word again adds a second one.
  await page.locator('.english-line').first().click()
  await expect(page.locator('.english-entry').first()).toHaveAttribute('data-mark-count', '2')
  await page.getByRole('slider', { name: '词组', exact: true }).focus(); await page.keyboard.press('ArrowRight')
  await expect.poll(async () => (await state(page)).learning.drafts.learn?.page).toBe(1)
  await page.reload()
  await expect(page.locator('.english-entry').first()).toHaveAttribute('data-word-id', initial.books[0].wordIds[20])
  await page.getByRole('button', { name: '上一组', exact: true }).click()
  await expect(page.locator('.english-entry[data-forgotten=true]')).toHaveCount(5)
  await submit(page).click()
  await expect.poll(async () => (await state(page)).reviews.length).toBe(20)
  const saved = await state(page)
  expect(saved.reviews.filter(r => r.rating === 1)).toHaveLength(5)
  expect(saved.reviews.filter(r => r.kind === 'learn')).toHaveLength(20)
  expect(saved.learning.receipts).toHaveLength(1)
  await expect(submit(page)).toHaveCount(0)
  await page.reload()
  await expect(page.locator('.study-submit-area')).toContainText('本组已检查完')
  await (await studyMenu(page)).getByRole('button', { name: '撤销上一步', exact: true }).click()
  await expect.poll(async () => (await state(page)).reviews.length).toBe(0)
  expect((await state(page)).words.filter(w => w.learned)).toHaveLength(0)
  await page.reload()
  await expect(page.locator('.english-entry[data-forgotten=true]')).toHaveCount(5)
  await submit(page).click()
  await expect.poll(async () => (await state(page)).reviews.length).toBe(20)
  expect((await state(page)).learning.receipts.map(r => r.status)).toEqual(['undone', 'saved'])
})

test('global due review can pause a new-word draft; practice leaves scheduling unchanged', async ({ page }) => {
  let initial = fsrsFixture(40)
  initial = installBook(initial, 'second', '第二词书', '合成测试', starterRows.slice(20, 50), 20)
  initial = reviewWord(initial, initial.words[0].id, 3, new Date(Date.now() - 30 * 60000))
  initial = reviewWord(initial, initial.words[25].id, 3, new Date(Date.now() - 30 * 60000))
  initial.activeBookId = 'personal'; initial.learning.view = 'learn'
  await seed(page, initial); await page.goto('/')
  const firstId = await page.locator('.english-entry').first().getAttribute('data-word-id')
  await page.locator('.english-line').first().click()
  const draftId = (await state(page)).learning.drafts.learn!.id
  await page.getByRole('button', { name: '到期复习', exact: true }).click()
  await expect(page.locator('.english-entry')).toHaveCount(2)
  await expect(page.locator('.current-book-label')).toHaveText('全部词书')
  await submit(page).click()
  await expect.poll(async () => (await state(page)).reviews.filter(r => r.kind === 'review').length).toBe(2)
  await page.getByRole('button', { name: '新词', exact: true }).click()
  await expect(page.locator('.english-entry').first()).toHaveAttribute('data-word-id', firstId!)
  expect((await state(page)).learning.drafts.learn!.id).toBe(draftId)
  await (await studyMenu(page)).getByRole('button', { name: /^回看当天/, exact: true }).click()
  const before = await state(page)
  await page.locator('.english-line').first().click()
  await page.getByRole('button', { name: '练习完成', exact: true }).click()
  await expect.poll(async () => !!(await state(page)).learning.practice?.completedAt).toBe(true)
  const after = await state(page)
  expect(after.words).toEqual(before.words)
  expect(after.reviews).toEqual(before.reviews)
  await page.reload()
  await expect(page.getByRole('button', { name: '练习完成', exact: true })).toBeDisabled()
})

test('a day finished on an earlier date offers the next day instead of an empty check-in', async ({ page }) => {
  let initial = importToPersonal({ ...emptyStore(), goal: 20 }, starterRows.slice(0, 60), '按天复习').store
  const yesterday = new Date(Date.now() - 26 * 3600000)
  for (const id of initial.books[0].wordIds.slice(0, 20)) initial = reviewWord(initial, id, 3, yesterday)
  await seed(page, initial)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(page.locator('.day-title')).toHaveText('第 1 天')
  await expect(page.getByRole('button', { name: '打卡', exact: true })).toHaveCount(0)
  await expect(page.locator('.checkin-bar')).toContainText('第 1 天已经学完')
  await page.getByRole('navigation', { name: '主导航' }).getByRole('tab', { name: '统计', exact: true }).click()
  await expect(page.getByRole('button', { name: /^第 1 天已经学完，进入第 2 天继续/ })).toBeVisible()
  await page.getByRole('navigation', { name: '主导航' }).getByRole('tab', { name: '学习', exact: true }).click()
  await page.getByRole('button', { name: '进入第 2 天', exact: true }).click()
  await expect(page.locator('.day-title')).toHaveText('第 2 天')
  await expect(page.getByRole('button', { name: '需要复习', exact: true })).toHaveText('需要复习 20')
  expect((await state(page)).checkins).toHaveLength(0)
})

test('艾宾浩斯 day 2 shows its new words and day-1 review; finishing both unlocks a check-in that counts in stats', async ({ page }) => {
  let initial = importToPersonal({ ...emptyStore(), goal: 20 }, starterRows.slice(0, 60), '按天复习').store
  const yesterday = new Date(Date.now() - 26 * 3600000)
  for (const id of initial.books[0].wordIds.slice(0, 20)) initial = reviewWord(initial, id, 3, yesterday)
  initial.books[0].currentDay = 1
  await seed(page, initial)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  const nav = page.getByRole('navigation', { name: '主导航' })
  await expect(page.locator('.day-title')).toHaveText('第 2 天')
  await expect(page.getByRole('button', { name: '当天新学', exact: true })).toHaveText('当天新学 20')
  await expect(page.getByRole('button', { name: '需要复习', exact: true })).toHaveText('需要复习 20')
  await expect(page.getByLabel('当天计划')).toHaveText('第 2 天 · 新学 20 词 · 复习 20 词（第 1 天学过的词）')
  await page.screenshot({ path: 'test-results/day-plan-390.png', animations: 'disabled' })
  await nav.getByRole('tab', { name: '统计', exact: true }).click()
  await expect(page.getByRole('button', { name: /^还差 新学 20 词、复习 20 词/ })).toBeVisible()
  await expect(page.getByRole('button', { name: /^打卡/ })).toHaveCount(0)
  await nav.getByRole('tab', { name: '学习', exact: true }).click()
  await page.getByRole('button', { name: '需要复习', exact: true }).click()
  await expect(page.locator('.english-entry')).toHaveCount(20)
  expect(await page.locator('.english-entry').evaluateAll(rows => rows.map(row => row.getAttribute('data-word-id')))).toEqual(initial.books[0].wordIds.slice(0, 20))
  await submit(page).click()
  await expect.poll(async () => (await state(page)).reviews.filter(r => r.forDay === 'personal:1')).toHaveLength(20)
  await expect(page.getByRole('button', { name: '需要复习', exact: true })).toHaveText('需要复习 0')
  await page.getByRole('button', { name: '当天新学', exact: true }).click()
  await expect(page.locator('.english-entry').first()).toHaveAttribute('data-word-id', initial.books[0].wordIds[20])
  await submit(page).click()
  await expect.poll(async () => (await state(page)).reviews.filter(r => r.kind === 'learn')).toHaveLength(20)
  await nav.getByRole('tab', { name: '统计', exact: true }).click()
  await page.getByRole('button', { name: '打卡 · 今天新学 20 词、复习 20 词', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: '今日已打卡' })).toHaveText('今日已打卡 · 新学 20 词 · 复习 20 词')
  await page.reload()
  if (await nav.getByRole('tab', { name: '统计', exact: true }).getAttribute('aria-selected') !== 'true') await nav.getByRole('tab', { name: '统计', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: '今日已打卡' })).toBeVisible()
  const saved = await state(page)
  expect(saved.checkins).toHaveLength(1)
  expect(saved.checkins[0]).toMatchObject({ bookId: 'personal', day: 1, newCount: 20, reviewCount: 20 })
  await expect(page.getByLabel('打卡记录').locator('.stats-figures > div').first()).toContainText('1连续打卡')
  await expect(page.getByLabel('最近 28 天打卡').locator('[data-today=true]')).toHaveAttribute('data-done', 'true')
  await expect(page.getByRole('listitem', { name: '今天 新学 20 复习 20', exact: true })).toBeVisible()
  for (const width of [320, 390, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: `test-results/stats-checkin-${width}.png`, animations: 'disabled' })
  }
})

test('failed submission keeps a pending copy and retry saves the same receipt exactly once', async ({ page }) => {
  await seed(page, fixture(20)); await page.goto('/')
  let fail = true
  await page.route('**/api/state', route => route.request().method() === 'PUT' && fail
    ? route.fulfill({ status: 503, json: { error: '合成保存失败' } }) : route.continue())
  await submit(page).click()
  await expect(page.getByRole('alert')).toContainText('当前改动尚未保存')
  expect((await state(page)).reviews).toHaveLength(0)
  await expect((await studyMenu(page)).getByRole('button', { name: /^回看当天/ })).toBeDisabled()
  await page.locator('ion-modal').getByRole('button', { name: '关闭', exact: true }).click()
  fail = false
  await page.getByRole('button', { name: '重试保存', exact: true }).click()
  await expect(page.locator('.save-problem')).toHaveCount(0)
  const saved = await state(page)
  expect(saved.reviews).toHaveLength(20)
  expect(saved.learning.receipts).toHaveLength(1)
  await page.reload()
  await (await studyMenu(page)).getByRole('button', { name: '撤销上一步', exact: true }).click()
  await expect.poll(async () => (await state(page)).reviews.length).toBe(0)
})

test('a lost save response is reconciled; a conflicting writer is never overwritten', async ({ page }) => {
  await seed(page, fixture(20)); await page.goto('/')
  let loseResponse = true
  await page.route('**/api/state', async route => {
    if (route.request().method() !== 'PUT' || !loseResponse) return route.continue()
    loseResponse = false
    await route.fetch(); await route.abort('failed')
  })
  await submit(page).click()
  await expect(page.locator('.study-submit-area')).toContainText('本组已检查完')
  await expect((await studyMenu(page)).getByRole('button', { name: /^回看当天/ })).toBeEnabled()
  expect((await state(page)).reviews).toHaveLength(20)
  await expect(page.locator('.save-problem')).toHaveCount(0)
  const concurrent = await state(page); concurrent.profile.nickname = '另一端'
  await seed(page, concurrent)
  await (await studyMenu(page)).getByRole('button', { name: /^回看当天/ }).click()
  await expect(page.getByRole('alert')).toContainText('其他操作已更新学习记录')
  await page.getByRole('button', { name: '重试保存' }).click()
  await expect(page.getByRole('alert')).toContainText('其他操作已更新学习记录')
  expect((await state(page)).profile.nickname).toBe('另一端')
  expect((await state(page)).learning.view).toBe('learn')
  await page.getByRole('button', { name: '放弃改动并重载' }).click()
  await page.getByRole('alertdialog').getByRole('button', { name: '放弃并重载', exact: true }).click()
  await expect(page.locator('.save-problem')).toHaveCount(0)
})

test('existing word order and day survive startup and import; draft UI fits mobile and desktop', async ({ page }) => {
  const initial = fixture(61)
  initial.books[0].wordIds.reverse(); initial.books[0].currentDay = 1
  await seed(page, initial); await page.goto('/')
  await expect(page.locator('.english-entry').first()).toHaveAttribute('data-word-id', initial.books[0].wordIds[40])
  expect((await state(page)).books).toEqual(initial.books)
  await page.locator('.english-line').first().click()
  await page.reload()
  for (const width of [320, 390, 430, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    expect(await page.locator('.study-task-tabs,.study-draft-note,.english-entry,.study-submit-area').evaluateAll(items => items.every(el => el.scrollWidth <= el.clientWidth))).toBe(true)
    await page.screenshot({ path: `test-results/study-draft-${width}.png`, animations: 'disabled' })
  }
  await page.getByRole('navigation', { name: '主导航' }).getByRole('tab', { name: '我的', exact: true }).click()
  await page.getByRole('button', { name: '管理目标词书', exact: true }).click()
  await page.getByRole('button', { name: '导入词表', exact: true }).click()
  await page.getByLabel('或粘贴词表').fill('word,meaning\nunseenfixture,新增测试词')
  await page.getByRole('button', { name: '加入我的词本', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  const saved = await state(page)
  expect(saved.books[0].wordIds.slice(0, 61)).toEqual(initial.books[0].wordIds)
  expect(saved.books[0].currentDay).toBe(1)
})

test('completion continues unfinished groups and later additions to the same Day', async ({ page }) => {
  const initial = fixture(40)
  initial.books[0].dailyCount = 50
  await seed(page, initial); await page.goto('/')
  await page.getByRole('slider', { name: '词组', exact: true }).focus(); await page.keyboard.press('ArrowRight')
  await submit(page).click()
  await expect.poll(async () => (await state(page)).reviews.length).toBe(20)
  await page.getByRole('button', { name: '继续下一组' }).click()
  await expect(page.locator('.english-entry').first()).toHaveAttribute('data-word-id', initial.books[0].wordIds[0])
  await submit(page).click()
  await expect.poll(async () => (await state(page)).reviews.length).toBe(40)
  await page.getByRole('navigation', { name: '主导航' }).getByRole('tab', { name: '我的', exact: true }).click()
  await page.getByRole('button', { name: '管理目标词书', exact: true }).click()
  await page.getByRole('button', { name: '导入词表', exact: true }).click()
  await page.getByLabel('或粘贴词表').fill('word,meaning\nnewdayfixture,本日追加词')
  await page.getByRole('button', { name: '加入我的词本', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: '继续当天新词' }).click()
  await expect(page.locator('.english-entry')).toHaveCount(1)
  await expect(page.locator('.english-entry')).toContainText('newdayfixture')
  await submit(page).click()
  await expect.poll(async () => (await state(page)).reviews.length).toBe(41)
})
