import { demoRows, type ImportRow } from './model'

const additional: [string, string][] = [
  ['ability', 'n. 能力；才能'],
  ['achieve', 'v. 实现；达到'],
  ['adapt', 'v. 适应；调整'],
  ['advantage', 'n. 优势；有利条件'],
  ['affect', 'v. 影响'],
  ['analyze', 'v. 分析'],
  ['approach', 'n. 方法；v. 接近'],
  ['assess', 'v. 评估；估计'],
  ['assume', 'v. 假定；承担'],
  ['aware', 'adj. 意识到的；知道的'],
  ['benefit', 'n. 益处；v. 受益'],
  ['challenge', 'n. 挑战；v. 质疑'],
  ['clarify', 'v. 澄清；阐明'],
  ['compare', 'v. 比较'],
  ['complete', 'v. 完成；adj. 完整的'],
  ['complex', 'adj. 复杂的'],
  ['concentrate', 'v. 集中注意力'],
  ['concern', 'n. 担忧；v. 涉及；使担心'],
  ['conclude', 'v. 得出结论；结束'],
  ['confident', 'adj. 自信的；有把握的'],
  ['consider', 'v. 考虑；认为'],
  ['construct', 'v. 建造；构建'],
  ['contribute', 'v. 贡献；促成'],
  ['create', 'v. 创造'],
  ['decline', 'v. 下降；婉拒'],
  ['define', 'v. 定义；明确'],
  ['demonstrate', 'v. 证明；演示'],
  ['develop', 'v. 发展；培养'],
  ['discover', 'v. 发现'],
  ['diverse', 'adj. 多种多样的'],
  ['efficient', 'adj. 高效的'],
  ['effort', 'n. 努力'],
  ['enable', 'v. 使能够'],
  ['enhance', 'v. 增强；提高'],
  ['ensure', 'v. 确保'],
  ['essential', 'adj. 必不可少的；本质的'],
  ['establish', 'v. 建立；确立'],
  ['evaluate', 'v. 评价；评估'],
  ['evidence', 'n. 证据'],
  ['expand', 'v. 扩大；扩展'],
  ['experience', 'n. 经验；经历；v. 经历'],
  ['explore', 'v. 探索；探究'],
  ['express', 'v. 表达'],
  ['flexible', 'adj. 灵活的；柔韧的'],
  ['focus', 'v. 集中；n. 焦点'],
  ['frequent', 'adj. 频繁的'],
  ['generate', 'v. 产生；生成'],
  ['identify', 'v. 识别；确定'],
  ['improve', 'v. 改善；提高'],
  ['include', 'v. 包括'],
  ['indicate', 'v. 表明；指示'],
  ['individual', 'n. 个人；adj. 个别的'],
  ['influence', 'n. 影响；v. 影响'],
  ['maintain', 'v. 维持；维护'],
  ['method', 'n. 方法'],
  ['obtain', 'v. 获得'],
  ['opportunity', 'n. 机会；时机'],
  ['outcome', 'n. 结果'],
  ['participate', 'v. 参加；参与'],
  ['patient', 'adj. 有耐心的；n. 病人'],
  ['persistent', 'adj. 坚持不懈的；持续的'],
  ['potential', 'adj. 潜在的；n. 潜力'],
  ['practical', 'adj. 实用的；实际的'],
  ['predict', 'v. 预测'],
  ['prefer', 'v. 更喜欢'],
  ['prevent', 'v. 阻止；预防'],
  ['priority', 'n. 优先事项；优先权'],
  ['process', 'n. 过程；v. 加工；处理'],
  ['progress', 'n. 进步；v. 进展'],
  ['promote', 'v. 促进；晋升'],
  ['provide', 'v. 提供'],
  ['purpose', 'n. 目的；意图'],
  ['recognize', 'v. 认出；承认'],
  ['reflect', 'v. 反映；反思'],
  ['reliable', 'adj. 可靠的'],
  ['require', 'v. 需要；要求'],
  ['resource', 'n. 资源'],
  ['respond', 'v. 回应；作出反应'],
  ['result', 'n. 结果；v. 导致'],
  ['significant', 'adj. 重要的；显著的'],
  ['solution', 'n. 解决办法；溶液'],
  ['specific', 'adj. 具体的；特定的'],
  ['strategy', 'n. 策略；战略'],
  ['support', 'v. 支持；n. 支持'],
  ['sustainable', 'adj. 可持续的'],
  ['tendency', 'n. 倾向；趋势'],
  ['transform', 'v. 转变；改造'],
  ['valuable', 'adj. 有价值的；宝贵的'],
]

export const starterRows: ImportRow[] = [
  ...demoRows,
  ...additional.map(([word, meaning]) => ({ word, meaning, phonetic: '', example: '' })),
]
